root/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main'

# urls.py
urlpatterns = [
    path('', views.homeview, name='home'),
    path('chatroom/<slug:roomcode>',views.chatroomview, name = 'chatroom'),
    path('joinchatroom/<slug:roomcode>', views.join_chatroom, name = 'joinchatroom'),
    path('leavechatroom/<slug:roomcode>', views.leave_chatroom, name = 'leavechatroom'),
    path('createchatroom/', views.create_chatroom, name = 'createchatroom'),
    path('searchview/', views.searchview, name = 'search'),
    path('user/<slug:username>', views.user_dashboard, name = 'userdashboard'),
    path('view_chatroom/<slug:roomcode>', views.chatroom_dashboard, name = 'chatroomdashboard'),
]

root/root/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/', 'api.urls'),
    path('user/', include('userprofiles.urls')),
    path('main/', include('main.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/main/models.py
from django.db import models
from userprofiles.models import user_profile
import datetime
# Create your models here.

class Chatroom(models.Model) :
    code =  models.CharField(max_length=7)
    name = models.CharField(max_length=20, unique=True)
    desc = models.TextField(max_length=500)

    def __str__(self):
        return f"{self.name}({self.code})"

class messages(models.Model) :
    chatroom = models.ForeignKey(Chatroom, on_delete=models.CASCADE, blank=True, null=True)
    content = models.TextField(max_length=1000)
    sender = models.ForeignKey(user_profile, on_delete=models.CASCADE)
    is_seen = models.BooleanField(default=0)
    date_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

class JoinedChatrooms(models.Model) :
    user = models.ForeignKey(user_profile,on_delete=models.CASCADE)
    chatroom = models.ForeignKey(Chatroom, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        existing_pair = JoinedChatrooms.objects.filter(user=self.user, chatroom=self.chatroom)

        if not existing_pair:
            super().save(*args, **kwargs)
        else:
            raise ValueError('A person with the same name and age already exists.')

    def __str__(self):
        return f"{self.chatroom} --> {self.user.user.username}"

root/main/forms.py
from django import forms
from django.forms import ModelForm

from .models import *
from userprofiles.models import *

class chatmessagecreationform(forms.ModelForm):
    class Meta:
        model = messages
        fields = ['content']

class ChatroomForm(forms.ModelForm):
    class Meta:
        model = Chatroom
        fields = ['name', 'desc']

class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = user_profile
        fields = ['pfp']

root/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db.models import Q

from .models import *
from .forms import *

from userprofiles.models import user_profile
from userprofiles.views import loginview
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.contrib import messages as django_messages

from .matchmaking import get_keywords

# Create your views here.

@login_required(login_url=loginview)
def searchview(request) :
    squery = request.GET['searchquery']
    asked_rooms = Chatroom.objects.filter(Q(desc__contains=squery)|Q(name__contains=squery))
    joined_chatrooms = Chatroom.objects.filter(joinedchatrooms__user=user_profile.objects.get(user=request.user))
    final_joined = []
    for chatroom in joined_chatrooms:
        final_joined.append(chatroom)

    context = {
        'rooms' : asked_rooms,
        'final_joined' : final_joined,
    }
    if request.method == 'POST' :
        s = request.POST['search']
        return redirect(f'/main/searchview/?searchquery={s}')
    return render(request, 'searchview.html', context=context)


@login_required(login_url=loginview)
def homeview(request) :
    user_profile_instance = user_profile.objects.get(user=request.user)
    joined_chatrooms = Chatroom.objects.filter(joinedchatrooms__user=user_profile_instance)
    not_joined_chatrooms = Chatroom.objects.exclude(joinedchatrooms__user=user_profile_instance)
    final_joined = []
    final_not_joined = []

    for chatroom in joined_chatrooms:
        final_joined.append(chatroom)

    for chatroom in not_joined_chatrooms:
        final_not_joined.append(chatroom)
    
    if request.method == 'POST' :
        s = request.POST['search']
        return redirect(f'/main/searchview/?searchquery={s}')

    keywords = get_keywords(user_profile_instance.bio)
    keywords = [x.lower() for x in keywords]
    print('===========================================')
    print(user_profile_instance.bio)
    print(keywords)
    suggested_rooms = []
    for room in final_not_joined :
        if len(list(set(keywords) & set(room.desc.split(' ')))) > 0:
            suggested_rooms.append(room)
    print('===========================================')

    try :
        asked_chatroom = request.GET['searchquery']
        chatrooms = Chatroom.objects.filter(name__contains = asked_chatroom)
        return HttpResponse(f"here are the results : ")
    except :
        pass

    all_chatrooms = Chatroom.objects.all()

    context = {
        'user' : user_profile_instance,
        'userr' : request.user,
        'joined_chatrooms' : set(final_joined),
        'other_chatrooms' : set(final_not_joined),
        'suggested_rooms' : set(suggested_rooms),
    }

    return render(request, 'home.html', context = context)

@login_required(login_url=loginview)
def chatroomview(request, roomcode) :
    user_profile_instance = user_profile.objects.get(user=request.user)
    chatroom = Chatroom.objects.get(code = roomcode)
    messages_list = messages.objects.filter(chatroom = chatroom)
    form = chatmessagecreationform(request.POST)
    joined_chatrooms = Chatroom.objects.filter(joinedchatrooms__user=user_profile_instance)
    try :
        JoinedChatrooms.objects.get(user = user_profile_instance, chatroom = chatroom)
        flag = "joined"
    except :
        flag = "not joined"

    context = {
        'chatroom' : chatroom,
        'user' : request.user,
        'messages' : messages_list,
        'form' : form,
        'roomcode' :roomcode,
        'joined_chatrooms' : joined_chatrooms,
        'flag' : flag,
    }

    if request.method == 'POST' :
        if form.is_valid() :
            message = form.save(commit = False)
            sender = user_profile.objects.get(user = request.user)
            message.sender = sender
            message.chatroom = chatroom
            message.save()
            return redirect(f'/main/chatroom/{roomcode}')

    return render(request, 'chatroom.html', context=context)

@login_required(login_url=loginview)
def user_dashboard(request, username):

    if username == request.user.username :
        profile = user_profile.objects.get(user = request.user)
        form = ProfilePictureForm(request.POST, request.FILES, instance=profile)
        # account holder is viewing his own dashboard :
        joined_chatrooms = JoinedChatrooms.objects.filter(user = profile)
        context = {
            'profile' : profile,
            'joined_chatrooms' : joined_chatrooms,
            'form' : form,
            'auth' : 'yes',
        }
        if request.method == 'POST':
            if form.is_valid():
                profile_f = form.save(commit=False)
                profile_f.save()
                return redirect(f"/main/user/{profile.user.username}")
        return render(request, "user_dashboard.html", context = context)
    else :
        profile = user_profile.objects.get(user = User.objects.get(username = username))
        joined_chatrooms = JoinedChatrooms.objects.filter(user = profile)
        context = {
            'profile' : profile,
            'joined_chatrooms' : joined_chatrooms,
            'auth' : 'no',
        }
        return render(request, "user_dashboard.html", context = context)

@login_required(login_url=loginview)
def chatroom_dashboard(request, roomcode):
    room = Chatroom.objects.get(code = roomcode)
    user = user_profile.objects.get(user = request.user)
    try :
        JoinedChatrooms.objects.get(chatroom = room, user = user)
        flag = "joined"
    except :
        flag = "not joined"
    
    members = JoinedChatrooms.objects.filter(chatroom = room)
    
    context = {
        'room' : room,
        'flag' : flag,
        'members' : members,
        'user' : request.user,
    }
    return render(request, 'chatroom_dashboard.html', context=context)

@login_required(login_url=loginview)
def join_chatroom(request, roomcode):
    room = Chatroom.objects.get(code = roomcode)
    user = user_profile.objects.get(user = request.user)
    JoinedChatrooms.objects.create(user = user, chatroom = room)
    return redirect('/main')

@login_required(login_url=loginview)
def leave_chatroom(request, roomcode):
    room = Chatroom.objects.get(code = roomcode)
    user = user_profile.objects.get(user = request.user)
    try :
        chatroom_to_leave = JoinedChatrooms.objects.get(user = user, chatroom = room)
        print(chatroom_to_leave)
        chatroom_to_leave.delete()
        return redirect('/main')
    except :
        return redirect('/main')
    
@login_required(login_url=loginview)
def create_chatroom(request):
    if request.method == 'POST':
        form = ChatroomForm(request.POST)
        if form.is_valid():
            chatroom = form.save(commit=False)
            chatroom.code = generate_random_code()
            chatroom.save()
            django_messages.success(request, 'Chatroom successfully created.')

        else:
            django_messages.error(request, 'This name is already taken.')
    else:
        form = ChatroomForm()
    return render(request, 'create_chatroom.html', {'form': form})


# ---------------------------- brain ------------------------------- :

import random

def generate_random_code(length=7):
    characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    random_string = ''.join(random.choice(characters) for _ in range(length))
    return random_string

root/main/templates/chatroom.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <title>{{chatroom.name}}</title>
    <link rel="stylesheet" href="{% static 'css/chatroom.css' %}" />
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <!-- HTMX link-->
  </head>
  <body>
    <div class="sidebar" id="sidebar">
      <div class="gohome-heading"><a href="/main">← Back to home</a></div>
      <div class="sidebar-heading">Chatrooms</div>
      <ul class="chatroom-list">
        <!-- List of all joined chatrooms -->
        {% for jc in joined_chatrooms %} {% if jc.name == chatroom.name %}
        <li>
          <a>
            <div class="chatroom-box" style="background-color: #3b5998">
              <a href="/main/chatroom/{{jc.code}}" class="chatroom-link"
                >{{jc.name}}</a
              >
              <div class="chatroom-description-small">{{jc.desc}}</div>
            </div>
          </a>
        </li>
        {% else %}
        <li>
          <a>
            <div class="chatroom-box">
              <a href="/main/chatroom/{{jc.code}}" class="chatroom-link"
                >{{jc.name}}</a
              >
              <div class="chatroom-description-small">{{jc.desc}}</div>
            </div>
          </a>
        </li>
        {% endif %} {% endfor %}
      </ul>
    </div>
    <input type="hidden" id="current-user" value="{{ user.username }}" />
    <div class="chatroom-container">
      <div class="chatroom-heading">{{chatroom.name}}</div>
      <div id="scrollable-div">
        <div id="chats">
          <div
            class="chatroom-description-small"
            style="color: black; text-align: center; opacity: 0.7"
          >
            "{{chatroom.desc}}"
          </div>
          {% for msg in messages %}
          <br />
          {% if msg.sender.user.username == user.username %}
          <div class="message sent-by-me">
            <div class="message-sender">You</div>
            <div class="message-content">{{msg.content}}</div>
            <div class="message-timestamp">{{msg.date_time}}</div>
          </div>
          {% else %}
          <div class="message received">
            <div class="message-sender">{{msg.sender.user.username}}</div>
            <div class="message-content">{{msg.content}}</div>
            <div class="message-timestamp">{{msg.date_time}}</div>
          </div>
          {% endif %} {% endfor %}
        </div>
      </div>
      <!-- Input Section -->
      <form method="post" class="input-section" id="msg_send_form">
        {% csrf_token %} {{form.content}} {% if flag == "joined" %}
        <button class="send-button" type="submit">Send</button>
        {% else %}
        <button class="send-button" disabled style="opacity: 0.5">
          Join room to send
        </button>
        {% endif %}
      </form>
    </div>
  </body>
  <script src="{% static 'js/chatroom.js' %}"></script>
</html>

root/main/templates/chatroom_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{room.name}}</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/chatroom_dashboard.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>
  <body>
    <nav class="navbar">
      <div class="navbar-left">
        <a href="/main" class="company-name">HealthBond</a>
      </div>
      <div class="navbar-right">
        <a href="/main/user/{{user.username}}" class="nav-item">Profile</a>
        <a href="/user/logout" class="nav-item">Logout</a>
      </div>
    </nav>
    <div class="dashboard-container">
      <div class="chatroom-details">
        <h2>{{room.name}}</h2>
        <p>{{room.desc}}</p>
        <div class="action-buttons">
          {% if flag == "joined" %}
          <button
            id="{{room.code}}"
            class="leave-button"
            onclick="leavechatroomfunc('{{room.code}}', this); pop_list('{{user.username}}', this)"
          >
            Leave
          </button>
          {% else %}
          <button
            id="{{room.code}}"
            class="join-button"
            onclick="joinchatroomfunc('{{room.code}}', this); append_list('{{user.username}}', this);"
          >
            Join
          </button>
          {% endif %}
          <button class="join-button">
            <a href="/main/chatroom/{{room.code}}">Enter Chatroom</a>
          </button>
        </div>
      </div>
      <div class="user-list">
        <h3>Users in Chatroom</h3>
        <ul id="member_list">
          {% for member in members %}
          <li class="user" id="{{member.user.user.username}}">
            <span class="username">{{member.user.user.username}}</span>
            <button class="view-button">
              <a href="/main/user/{{member.user.user.username}}">View</a>
            </button>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </body>
  <script src="{% static 'js/room_view_operations.js' %}"></script>
</html>

root/main/templates/create_chatroom.html
<!DOCTYPE html>
<html>
  <head>
    <title>Create Chatroom</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <style>
      body {
        font-family: "inter", sans-serif;
        margin: 0px;
        padding: 0px;
      }
      .navbar {
        display: flex;

        justify-content: space-between;
        align-items: center;
        background-color: #6964ff;
        padding: 10px 20px;
        color: white;
        margin-bottom: 20px;
      }

      .navbar-left {
        flex: 1;
      }

      .company-name {
        text-decoration: none;
        color: white;
        font-size: 24px;
        font-weight: bold;
      }

      .navbar-right {
        display: flex;
        gap: 15px;
      }

      .nav-item {
        text-decoration: none;
        color: white;
        font-size: 18px;
        padding: 5px 10px;
        border-radius: 5px;
        transition: background-color 0.3s;
      }

      .nav-item:hover {
        background-color: #5f1aff;
      }

      .form-container {
        width: 70%;
        margin: auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }

      .form-field {
        margin-bottom: 15px;
      }

      .form-field label {
        display: block;
        margin-bottom: 5px;
      }

      .form-field input,
      .form-field textarea {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
      }

      .form-field input[type="submit"] {
        width: auto;
        background-color: #4caf50;
        color: white;
        border: none;
        cursor: pointer;
        padding: 10px 20px;
        border-radius: 5px;
      }

      .form-field input[type="submit"]:hover {
        background-color: #45a049;
      }
      .messages {
        margin-bottom: 20px;
        padding: 10px;
        border-radius: 5px;
      }

      .messages.success {
        background-color: #dff0d8;
        color: #3c763d;
      }

      .messages.error {
        background-color: #f2dede;
        color: #a94442;
      }

      .errorlist {
        color: #a94442;
      }
    </style>
  </head>
  <body>
    <nav class="navbar">
      <div class="navbar-left">
        <a href="/main" class="company-name">HealthBond</a>
      </div>
      <div class="navbar-right">
        <a href="/main/user/{{user.username}}" class="nav-item">Profile</a>
        <a href="/user/logout" class="nav-item">Logout</a>
      </div>
    </nav>
    {% if messages %}
    <div class="messages-container">
      {% for message in messages %}
      <div class="messages {{ message.tags }}">{{ message }}</div>
      {% endfor %}
    </div>
    {% endif %}
    <div class="form-container">
      <h2>Create a New Chatroom</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-field">
          <label for="id_name">Name</label>
          {{ form.name }}
        </div>
        <div class="form-field">
          <label for="id_desc">Description</label>
          {{ form.desc }}
        </div>
        <div class="form-field">
          <input type="submit" value="Create Chatroom" />
        </div>
      </form>
    </div>
  </body>
</html>

root/main/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HealthBond - Connecting Health Enthusiasts</title>
    <link rel="stylesheet" href="style.css" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />

    <!-- ===== BOX ICONS ===== -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <style>
      body {
        font-family: "inter", sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f5f5f5;
      }

      .navbar {
        display: flex;
        justify-content: space-between;
        align-items: center;
        background-color: #6964ff;
        padding: 10px 20px;
        color: white;
      }

      .navbar-left {
        flex: 1;
      }

      .company-name {
        text-decoration: none;
        color: white;
        font-size: 24px;
        font-weight: bold;
      }

      .navbar-right {
        display: flex;
        gap: 15px;
      }

      .nav-item {
        text-decoration: none;
        color: white;
        font-size: 18px;
        padding: 5px 10px;
        border-radius: 5px;
        transition: background-color 0.3s;
      }

      .nav-item:hover {
        background-color: #5f1aff;
      }

      .container {
        max-width: 800px;
        margin: 50px auto;
        text-align: center;
        position: relative;
      }
      h1 {
        color: #333;
      }
      .widget {
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        margin-top: 30px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      .chatrooms {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 20px;
        margin-top: 20px;
      }
      .chatroom {
        background-color: #f0f0f0;
        border-radius: 5px;
        padding: 10px 20px;
        cursor: pointer;
        transition: background-color 0.3s ease;
      }
      .chatroom:hover {
        background-color: #e0e0e0;
      }
      .logout-btn {
        position: absolute;
        top: 20px;
        right: 20px;
        background-color: #ff6347;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        cursor: pointer;
        transition: background-color 0.3s ease;
      }
      .logout-btn:hover {
        background-color: #d14830;
      }
      .user-icon {
        position: absolute;
        top: 20px;
        right: 80px;
        width: 40px;
        height: 40px;
        border-radius: 50%;
        background-color: #337ab7;
        color: #fff;
        font-size: 24px;
        display: flex;
        align-items: center;
        justify-content: center;
      }
    </style>
  </head>
  <body>
    <nav class="navbar">
      <div class="navbar-left">
        <a href="/main" class="company-name">HealthBond</a>
      </div>
      <div class="navbar-right">
        <a href="/main/user/{{userr.username}}" class="nav-item">Profile</a>
        <a href="/user/logout" class="nav-item">Logout</a>
      </div>
    </nav>
    <div class="container">
      <h1>Welcome to HealthBond, {{user.user.username}}</h1>
      <h6>"{{user.bio}}"</h6>

      <form class="input-group mb-3" method="post">
        {% csrf_token %}
        <input
          type="text"
          class="form-control"
          placeholder="Search Chatrooms"
          aria-label="Recipient's username"
          aria-describedby="basic-addon2"
          name="search"
        />
        <span type="submit" class="input-group-text" id="basic-addon2"
          >Search</span
        >
      </form>

      <div class="widget">
        <h2>Chatrooms joined by you :</h2>
        <div class="chatrooms">
          {% for room in joined_chatrooms %}
          <div class="chatroom">
            <a href="view_chatroom/{{room.code}}">{{room.name}} </a>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="widget">
        <h2>Chatrooms suggested for you :</h2>
        <div class="chatrooms">
          {% for room in suggested_rooms %}
          <div class="chatroom">
            <a href="view_chatroom/{{room.code}}">{{room.name}} </a>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="widget">
        <h2>Chatrooms you can join :</h2>
        <div class="chatrooms">
          {% for room in other_chatrooms %}
          <div class="chatroom">
            <a href="view_chatroom/{{room.code}}">{{room.name}} </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </body>
</html>

root/main/templates/searchview.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <title>Search Results</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/search.css' %}" />
    <style></style>
  </head>
  <body>
    <form class="input-group mb-3" method="post">
      {% csrf_token %}
      <input
        type="text"
        class="form-control"
        placeholder="Search for chatrooms..."
        aria-describedby="basic-addon2"
        name="search"
      />
      <span type="submit" class="input-group-text" id="basic-addon2"
        >Search</span
      >
    </form>
    <div class="results-container">
      {% for room in rooms %}
      <div class="user-box">
        <div class="user-info">
          <div class="user-name">{{room.name}}</div>
          <div class="user-bio">{{room.desc}}</div>
        </div>
        {% if room in final_joined %}
        <button
          class="view-button"
          id="{{room.code}}"
          style="background-color: #ee4e4e"
          onclick="leavechatroomfunc('{{room.code}}',this)"
        >
          <a>Leave</a>
        </button>
        {% else %}
        <button
          class="view-button"
          onclick="joinchatroomfunc('{{room.code}}', this)"
        >
          <a>Join</a>
        </button>
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </body>
  <script src="{% static 'js/search_room_op.js' %}"></script>
</html>

root/main/templates/user_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <title>User Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/user_dashboard.css' %}" />
  </head>
  <body>
    <div class="dashboard-container">
      <div class="profile-section">
        {% if profile.pfp.url != default_image_url %}
        <img src="{{profile.pfp.url}}" alt="User Image" class="profile-image" />
        {% else %}

        <img
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/2048px-Default_pfp.svg.png"
          alt="User Image"
          class="profile-image"
        />
        {% if auth == "yes" %}
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} {{ form.pfp }}
          <button type="submit">Save</button>
        </form>
        {% else %} {% endif %} {% endif %}
        <h2>{{profile.user.first_name}} {{profile.user.last_name}}</h2>
        <p>@{{profile.user.username}}</p>
        <p>{{profile.bio}}</p>
      </div>
      <div class="details-section">
        <h3>Joined Chatrooms</h3>
        <div class="chatrooms-list">
          {% for room in joined_chatrooms %}
          <div class="chatroom">
            <div class="chatroom-details">
              <h4>{{room.chatroom.name}}</h4>
              <p>{{room.chatroom.desc}}</p>
            </div>
            <a
              href="/main/view_chatroom/{{room.chatroom.code}}"
              class="view-button"
              >View</a
            >
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </body>
</html>